import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.cwd()

const VERSION_SOURCE = join(root, 'proto', 'src', 'version.txt')
const VERSION_OUTPUT = join(root, 'src', 'version.ts')

/**
 * Reads the proto schema version from the submodule and regenerates src/version.ts.
 */
const main = (): void => {
  const version = readFileSync(VERSION_SOURCE, 'utf8').trim()
  if (!version) {
    throw new Error(`empty schema version at ${VERSION_SOURCE}`)
  }

  const content = `// Generated by scripts/version.ts — the proto schema version this binding targets.\nexport const SCHEMA_VERSION = '${version}'\n`

  writeFileSync(VERSION_OUTPUT, content)
  console.log(`SCHEMA_VERSION = ${version} -> src/version.ts`)
}

main()
